spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb?currentSchema=public
    username: postgres
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9003
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: BASIC

app:
  security:
    audience: order-service