spring:
  application:
    name: ms-identity
server:
  port: 9000
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  jwt:
    issuer: "http://localhost:${server.port}"
    expiry-seconds: 3600
    scope: "svc1.read svc1.write"
    audience:
      - customer-service
      - order-service
      - payment-service
      - product-service
