spring:
  application:
    name: ms-product
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb?currentSchema=public
    username: postgres
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: product-orders-consumer
      # JSON üçün:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        # JsonDeserializer üçün default type və trust:
        spring.json.value.default.type: az.rahibjafar.msproduct.event.model.OrderCreatedEvent
        spring.json.trusted.packages: "*"

      # Yeni consumer başladıqda əvvəlki mesajları da götürmək üçün (dev):
      auto-offset-reset: earliest

      # Manual ack istifadə edəcəyik (istəyə bağlı)
      enable-auto-commit: false

    # Producer yalnız DLT-yə publish üçün lazım olacaq (retry annotasiyası ilə)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Admin (topic auto-create üçün)
    admin:
      auto-create: true

server:
  port: 9001
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    config-url: /api-docs/swagger-config
    url: /api-docs
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  security:
    audience: product-service