spring:
  application:
    name: ms-product
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb?currentSchema=public
    username: postgres
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "az.rahibjafar.*,*"

      auto-offset-reset: earliest
      enable-auto-commit: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    admin:
      auto-create: true

server:
  port: 9001
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    config-url: /api-docs/swagger-config
    url: /api-docs
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  security:
    audience: product-service

kafka:
  groups:
    created: product-orderCreated-consumer
    cancelled: product-orderCancelled-consumer
  ids:
    created: product-orderCreated-c
    cancelled: product-orderCancelled-c